In [77]:
#Задание:
#Написать функцию, которая подсчитывает число покупателей, попадающих в каждую группу, 
#если нумерация ID сквозная и начинается с 0.
#На вход функция получает целое число n_customers (количество клиентов).

import pandas

IdList0 = [0, 1, 11, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 111111111] #список с ID

print('введите количество пользователей n_customers')
n_customers = int(input()) #ввод количества пользователей

def NumIdInGroup(n_customers):
    WorkList = IdList0[:n_customers]   # указываем, с чем работаем
       #считаем номер группы для id
    GroupList = []
    for val in WorkList:
        sum = 0
        while val > 0:
            digit = val % 10
            sum += digit
            val = val // 10
        GroupList.append(sum)
        
    # Находим уникальные значения групп
    GroupListUV = []
    for val in GroupList:
        if val not in GroupListUV:
            GroupListUV.append(val)

    # Находим количество покупателей для каждой группы
    NumIdInGroupList = []
    for val in GroupListUV:
        count = 0
        for idx in range(len(GroupList)):
            if val == GroupList[idx]:
                count += 1
        NumIdInGroupList.append(count)
        
    df1 = pandas.DataFrame({'Номер группы': GroupListUV,
                           'Число покупателей': NumIdInGroupList})
    return df1

NumIdInGroup(n_customers)

введите количество пользователей n_customers
4

   Номер группы  Число покупателей
0             0                  1
1             1                  1
2             2                  2

In [81]:
#Задание:
#Написать функцию, аналогичную первой, (которая подсчитывает число покупателей, попадающих в каждую группу)
#если ID начинается с произвольного числа.
#На вход функция получает целые числа: n_customers (количество клиентов) 
#и n_first_id (первый ID в последовательности).

#Комментарий
# n_first_id ассоциируется с Номером ID, а "первый ID" ассоциируется со значением ID
# делаю для n_first_id = Номер ID в списке

import pandas

IdList0 = [0, 1, 11, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 111111111] #список с ID

print('введите количество пользователей n_customers')
n_customers = int(input()) #ввод количества пользователей
print('номер ID, с которого начинать')
n_first_id = int(input()) #ввод количества пользователей


def NumIdInGroupSlice(n_customers, n_first_id):
    WorkList = IdList0[n_first_id:(n_first_id+n_customers)]   # указываем, с чем работаем
       #считаем номер группы для id
    GroupList = []
    for val in WorkList:
        sum = 0
        while val > 0:
            digit = val % 10
            sum += digit
            val = val // 10
        GroupList.append(sum)
        
    # Находим уникальные значения групп
    GroupListUV = []
    for val in GroupList:
        if val not in GroupListUV:
            GroupListUV.append(val)

    # Находим количество покупателей для каждой группы
    NumIdInGroupList = []
    for val in GroupListUV:
        count = 0
        for idx in range(len(GroupList)):
            if val == GroupList[idx]:
                count += 1
        NumIdInGroupList.append(count)
        
    df2 = pandas.DataFrame({'Номер группы': GroupListUV,
                           'Число покупателей': NumIdInGroupList})
        
    return df2

NumIdInGroupSlice(n_customers, n_first_id)

введите количество пользователей n_customers
4
номер ID, с которого начинать
0

   Номер группы  Число покупателей
0             0                  1
1             1                  1
2             2                  2